version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    target-branch: "master"
    schedule:
      interval: "daily
    allow:
      # Allow updates for allure-testng
      - dependency-name: "com.squareup.okhttp3:okhttp"
    reviewers:
      - "Viktor-Pylypenko"
