name: Create PR when package version is updated

on:
  workflow_run:
    workflows: [Main Action]
    types:
      - completed
    
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    
      - name: Check out a copy of repository in a workflow run
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: '11'
          
      - name: Create new Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
      
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      
  on-skip:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'skipped' }}
    steps:
      - run: echo 'The triggering workflow skipped'
