name: Create PR when package version is updated

on:
  workflow_run:
    workflows: [Main Action]
    types:
      - completed
    
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    
      - name: Check out a copy of repository in a workflow run
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: '11'
          
      - name: Create new Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""
          destination_branch: "master"
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: |
            :crown: *An automated PR*
            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          pr_reviewer: "Viktor-Pylypenko"
      
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      
  on-skip:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'skipped' }}
    steps:
      - run: echo 'The triggering workflow skipped'
