name: airSlate Bots tests

on:
  workflow_call:
    inputs:
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        required: false
      ALLURE_JOB_RUN_ID:
        type: string
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        type: string
        description: "ALLURE_USERNAME service parameter. Leave blank."
        required: false      

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
          
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.8.1
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Prepare AQL filter
        id: allure_filter
        run: echo "filter_data=cf[\"Repo\"] = \"${{ env.AIRSLATE_ADDON_SERVICE_NAME }}\" and status in [\"Automated\", \"In Release\"]" >> $GITHUB_OUTPUT
        env:
          AIRSLATE_ADDON_SERVICE_NAME: ${{ inputs.ADDON_SERVICE }}
          
      - name: Prepare TestPlan
        run: echo '${{ env.ALLURE_AQL_FILTER }}'
        env:
          ALLURE_AQL_FILTER: ${{ steps.allure_filter.outputs.filter_data }}
          
      - name: Print inputs
        run: |
          echo "The AIRSLATE_ENV_URL is ${{ inputs.AIRSLATE_ENV_URL }}"
          echo "The VIRTUAL_ENVIRONMENT is ${{ inputs.VIRTUAL_ENVIRONMENT }}"
          echo "The ADDON_SERVICE is ${{ inputs.ADDON_SERVICE }}"
