name: Main Action

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'pom.xml'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out a copy of repository in a workflow run
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Check out a copy of repository in a workflow run
      run: echo "Build completed ..."
