name: airSlate Bots tests

on:
  workflow_dispatch:
    inputs:
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
        default: https://airslate.com
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        default: calculate-addon
        required: false
      ALLURE_JOB_RUN_ID:
        type: string
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        type: string
        description: "ALLURE_USERNAME service parameter. Leave blank."
        required: false 
  workflow_call:
    inputs:
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
        default: https://airslate.com
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        default: calculate-addon
        required: false
      ALLURE_JOB_RUN_ID:
        type: string
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        type: string
        description: "ALLURE_USERNAME service parameter. Leave blank."
        required: false      

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
          
      - name: Set vars from workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "AIRSLATE_ENV_URL=${{ github.event.inputs.AIRSLATE_ENV_URL }}" >> $GITHUB_ENV
          echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> $GITHUB_ENV
          echo "ADDON_SERVICE=${{ github.event.inputs.ADDON_SERVICE }}" >> $GITHUB_ENV
          
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.8.1
          
      - name: Cache Maven packages
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Prepare AQL filter
        id: allure_filter
        run: echo ::set-output name=filter_data::'cf["Repo"] = "${{ env.AIRSLATE_ADDON_SERVICE_NAME }}" and status in ["Automated", "In Release"]'
        env:
          AIRSLATE_ADDON_SERVICE_NAME: ${{ env.ADDON_SERVICE }}
          
      - name: Prepare TestPlan
        run: echo '${{ env.ALLURE_AQL_FILTER }}'
        env:
          ALLURE_AQL_FILTER: ${{ steps.allure_filter.outputs.filter_data }}
