name: Reuse for concrete bot

on:
  workflow_dispatch:
    inputs: 
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
        default: https://airslate.com
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        required: true
        default: calculate-addon

jobs:        
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
        url: ${{ steps.env.outputs.AIRSLATE_ENV_URL }}
        venv: ${{ steps.addon.outputs.VIRTUAL_ENVIRONMENT }}
        service: ${{ steps.venv.outputs.ADDON_SERVICE }}
    steps:
    
    - name: Set AIRSLATE_ENV_URL variable
      id: env
      run: |
        if ${{ github.event_name == 'repository_dispatch' }}; then
          case ${{ github.event.client_payload.environment }} in 
            as-stage)
              echo "AIRSLATE_ENV_URL=https://airslate-stage.xyz" >> $GITHUB_OUTPUT
              ;;
           *)
              echo "AIRSLATE_ENV_URL=https://airslate.com" >> $GITHUB_OUTPUT
              ;;
          esac
        else
          echo "AIRSLATE_ENV_URL=${{ github.event.inputs.AIRSLATE_ENV_URL }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
      
    - name: Set ADDON_SERVICE variable
      id: addon
      run: |
        if [ ${{ github.event_name == 'repository_dispatch' }} ]; then
          echo "ADDON_SERVICE=${{ github.event.client_payload.service }}" >> $GITHUB_OUTPUT
        else
          echo "ADDON_SERVICE=${{ github.event.inputs.ADDON_SERVICE }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
      
    - name: Set VIRTUAL_ENVIRONMENT variable
      id: venv
      run: |
        if [ ${{ github.event_name == 'repository_dispatch' }} ]; then
          echo "VIRTUAL_ENVIRONMENT=${{ github.event.client_payload.venv }}" >> $GITHUB_OUTPUT
        else
          echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> $GITHUB_OUTPUT
        fi
      shell: bash

  run-tests:
    needs: prepare-variables
    uses: ./.github/workflows/main-bot-flow.yml
    with:
      AIRSLATE_ENV_URL: ${{needs.prepare-variables.outputs.url}}
      VIRTUAL_ENVIRONMENT: ${{needs.prepare-variables.outputs.venv}}
      ADDON_SERVICE: ${{needs.prepare-variables.outputs.service}}
