name: Reuse for concrete bot

on:
  workflow_dispatch:
    inputs: 
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
        default: https://airslate-stage.xyz
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
        default: default
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        required: true
        default: calculate-addon
env:
  AIRSLATE_ENV_URL: ${{ inputs.AIRSLATE_ENV_URL }}
  VIRTUAL_ENVIRONMENT: ${{ inputs.VIRTUAL_ENVIRONMENT }}
  ADDON_SERVICE: ${{ inputs.ADDON_SERVICE }}

jobs:        
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
        url: ${{ steps.vars.outputs.AIRSLATE_ENV_URL }}
        service: ${{ steps.vars.outputs.ADDON_SERVICE }}
        venv: ${{ steps.vars.outputs.VIRTUAL_ENVIRONMENT }}
    steps:
    
    - name: Get variables depending on the workflow trigger
      id: vars
      run: |
        case ${{ github.event_name }} in 
          workflow_dispatch)
            echo "ADDON_SERVICE=${{ github.event.inputs.ADDON_SERVICE }}" >> $GITHUB_OUTPUT

            if [[ "${{ github.event.inputs.AIRSLATE_ENV_URL }}" == "as-stage" && "${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" == "default" ]]; then
              echo "AIRSLATE_ENV_URL=https://airslate-stage.xyz" >> $GITHUB_OUTPUT
              echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.inputs.AIRSLATE_ENV_URL }}" == "as-stage" ]]; then
              echo "VIRTUAL_ENVIRONMENT=" >> $GITHUB_OUTPUT
              echo "AIRSLATE_ENV_URL=https://airslate-stage.xyz" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.inputs.AIRSLATE_ENV_URL }}" == "as-prod-au" ]]; then
              echo "AIRSLATE_ENV_URL=https://airslate-au.com" >> $GITHUB_OUTPUT
              echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> $GITHUB_OUTPUT
            else
              echo "AIRSLATE_ENV_URL=https://airslate.com" >> $GITHUB_OUTPUT
              echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> $GITHUB_OUTPUT
            fi
            ;;

        esac
      shell: bash
      
    - name: Print inputs
      run: |
        echo "The AIRSLATE_ENV_URL is ${{ needs.prepare-variables.outputs.url }}"
        echo "The VIRTUAL_ENVIRONMENT is ${{ needs.prepare-variables.outputs.venv }}"
        echo "The ADDON_SERVICE is ${{ needs.prepare-variables.outputs.service }}"

  run-tests:
    needs: prepare-variables
    uses: ./.github/workflows/main-bot-flow.yml
    with:
      AIRSLATE_ENV_URL: ${{needs.prepare-variables.outputs.url}}
      VIRTUAL_ENVIRONMENT: ${{needs.prepare-variables.outputs.venv}}
      ADDON_SERVICE: ${{needs.prepare-variables.outputs.service}}
