name: Reuse for concrete bot

on:
  workflow_dispatch:
    inputs:
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
        default: https://airslate.com
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        required: true
        default: calculate-addon          

jobs:        
  prepare-vars:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    outputs:
        output1: ${{ steps.step1.outputs.AIRSLATE_ENV_URL }}
        output2: ${{ steps.step2.outputs.VIRTUAL_ENVIRONMENT }}
        output3: ${{ steps.step3.outputs.ADDON_SERVICE }}
    steps:
    - name: step1
      id: step1
      run: echo "AIRSLATE_ENV_URL=${{ github.event.inputs.AIRSLATE_ENV_URL }}" >> "$GITHUB_OUTPUT"
    - name: step2  
      id: step2
      run: echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> "$GITHUB_OUTPUT"
    - name: step2
      id: step3
      run: echo "ADDON_SERVICE=${{ github.event.inputs.ADDON_SERVICE }}" >> "$GITHUB_OUTPUT"
      
  run-tests:
    needs: prepare-vars
    uses: ./.github/workflows/maven-publish.yml
    with:
      AIRSLATE_ENV_URL: ${{needs.prepare-vars.outputs.output1}}
      VIRTUAL_ENVIRONMENT: ${{needs.prepare-vars.outputs.output2}}
      ADDON_SERVICE: ${{needs.prepare-vars.outputs.output3}}

          
