name: Reuse for concrete bot

on:
  workflow_dispatch:
    inputs: 
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
        default: https://airslate.com
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        required: true
        default: calculate-addon

jobs:        
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
        url: ${{ steps.vvv.outputs.AIRSLATE_ENV_URL }}
        service: ${{ steps.vvv.outputs.ADDON_SERVICE }}
        venv: ${{ steps.vvv.outputs.VIRTUAL_ENVIRONMENT }}
    steps:
    
    - name: test variable
      id: vvv
      run: |
        case ${{ github.event_name }} in 
          repository_dispatch)
            echo "repository_dispatch case"
            echo "ADDON_SERVICE=${{ github.event.client_payload.service }}" >> $GITHUB_OUTPUT
            echo "VIRTUAL_ENVIRONMENT=${{ github.event.client_payload.venv }}" >> $GITHUB_OUTPUT

            if ${{ github.event.client_payload.environment }} = "as-stage"; then
              echo "AIRSLATE_ENV_URL=https://airslate-stage.xyz" >> $GITHUB_OUTPUT
            else
              echo "AIRSLATE_ENV_URL=https://airslate.com" >> $GITHUB_OUTPUT
            fi
            ;;

          workflow_dispatch)
            echo "workflow_dispatch case"
            echo "AIRSLATE_ENV_URL=${{ github.event.inputs.AIRSLATE_ENV_URL }}" >> $GITHUB_OUTPUT
            echo "ADDON_SERVICE=${{ github.event.inputs.ADDON_SERVICE }}" >> $GITHUB_OUTPUT
            echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> $GITHUB_OUTPUT
            ;; 
        esac
      shell: bash

  run-tests:
    needs: prepare-variables
    uses: ./.github/workflows/main-bot-flow.yml
    with:
      AIRSLATE_ENV_URL: ${{needs.prepare-variables.outputs.url}}
      VIRTUAL_ENVIRONMENT: ${{needs.prepare-variables.outputs.venv}}
      ADDON_SERVICE: ${{needs.prepare-variables.outputs.service}}
