name: Reuse for concrete bot

on:
  workflow_dispatch:
    inputs: 
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
        default: https://airslate.com
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        required: true
        default: calculate-addon          

jobs:        
  prepare-vars-workflow-dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
    - name: Set vars from workflow_dispatch
      run: |
        echo "AIRSLATE_ENV_URL=${{ github.event.inputs.AIRSLATE_ENV_URL }}" >> $GITHUB_ENV
        echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> $GITHUB_ENV
        echo "ADDON_SERVICE=${{ github.event.inputs.ADDON_SERVICE }}" >> $GITHUB_ENV
      
  prepare-vars-repository-dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch' }}
    steps:
    - name: Set vars from repository_dispatch
      run: |
        echo "ADDON_SERVICE=${{ github.event.client_payload.service }}" >> $GITHUB_ENV
        echo "ENV=${{ github.event.client_payload.environment }}" >> $GITHUB_ENV
        echo "VIRTUAL_ENVIRONMENT=${{ github.event.client_payload.venv }}" >> $GITHUB_ENV
        case ${{ github.event.client_payload.environment }} in
          as-stage)
            echo "AIRSLATE_ENV_URL=https://airslate-stage.xyz" >> $GITHUB_ENV
            ;;
          *)
            echo "AIRSLATE_ENV_URL=https://airslate.com" >> $GITHUB_ENV
            ;;
        esac

  run-tests:
    needs: [prepare-vars-workflow-dispatch, prepare-vars-repository-dispatch]
    if: |
      always() && 
      (needs.prepare-vars-workflow-dispatch.result == 'success' || needs.prepare-vars-workflow-dispatch.result == 'skipped') && 
      (needs.prepare-vars-repository-dispatch.result == 'success' || needs.prepare-vars-repository-dispatch.result == 'skipped') && 
      !(needs.prepare-vars-workflow-dispatch.result == 'skipped' && needs.prepare-vars-repository-dispatch.result == 'skipped')
    uses: ./.github/workflows/main-bot-flow.yml
    with:
      AIRSLATE_ENV_URL: ${{ env.AIRSLATE_ENV_URL }}
      VIRTUAL_ENVIRONMENT: ${{ env.VIRTUAL_ENVIRONMENT }}
      ADDON_SERVICE: ${{ env.ADDON_SERVICE }}
