name: Reuse for concrete bot

on:
  workflow_dispatch:
    inputs:
      AIRSLATE_ENV_URL:
        type: string
        description: "Endpoint for tests."
        required: true
        default: https://airslate.com
      VIRTUAL_ENVIRONMENT:
        type: string
        description: "Virtual environment."
        required: false
      ADDON_SERVICE:
        type: string
        description: "Addon service name."
        required: true
        default: calculate-addon          

jobs:        
  prepare-vars-workflow-dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    outputs:
        output1: ${{ steps.step1.outputs.AIRSLATE_ENV_URL }}
        output2: ${{ steps.step2.outputs.VIRTUAL_ENVIRONMENT }}
        output3: ${{ steps.step3.outputs.ADDON_SERVICE }}
    steps:
    - name: step1
      id: step1
      run: echo "AIRSLATE_ENV_URL=${{ github.event.inputs.AIRSLATE_ENV_URL }}" >> "$GITHUB_OUTPUT"
    - name: step2  
      id: step2
      run: echo "VIRTUAL_ENVIRONMENT=${{ github.event.inputs.VIRTUAL_ENVIRONMENT }}" >> "$GITHUB_OUTPUT"
    - name: step2
      id: step3
      run: echo "ADDON_SERVICE=${{ github.event.inputs.ADDON_SERVICE }}" >> "$GITHUB_OUTPUT"
      
  prepare-vars-repository-dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch' }}
    outputs:
        output1: ${{ steps.step1.outputs.AIRSLATE_ENV_URL }}
        output2: ${{ steps.step2.outputs.VIRTUAL_ENVIRONMENT }}
        output3: ${{ steps.step3.outputs.ADDON_SERVICE }}
    steps:
    - name: step1
      id: step1
      run: |
        case ${{ github.event.client_payload.environment }} in
          as-stage)
            echo "AIRSLATE_ENV_URL=https://airslate-stage.xyz" >> $GITHUB_OUTPUT
            ;;
            *)
            echo "AIRSLATE_ENV_URL=https://airslate.com" >> $GITHUB_OUTPUT
            ;;
        esac
    - name: step2  
      id: step2
      run: echo "VIRTUAL_ENVIRONMENT=${{ github.event.client_payload.venv }}" >> "$GITHUB_OUTPUT"
    - name: step2
      id: step3
      run: echo "ADDON_SERVICE=${{ github.event.client_payload.service }}" >> "$GITHUB_OUTPUT"
      
  run-tests:
    needs: [prepare-vars-workflow-dispatch, prepare-vars-repository-dispatch]
    if: |
      always() && 
      (needs.prepare-vars-workflow-dispatch.result == 'success' || needs.prepare-vars-workflow-dispatch.result == 'skipped') && 
      (needs.prepare-vars-repository-dispatch.result == 'success' || needs.prepare-vars-repository-dispatch.result == 'skipped') && 
      !(needs.prepare-vars-workflow-dispatch.result == 'skipped' && needs.prepare-vars-repository-dispatch.result == 'skipped')
    uses: ./.github/workflows/main-bot-flow.yml
    with:
      AIRSLATE_ENV_URL: ${{needs.prepare-vars.outputs.output1}}
      VIRTUAL_ENVIRONMENT: ${{needs.prepare-vars.outputs.output2}}
      ADDON_SERVICE: ${{needs.prepare-vars.outputs.output3}}

          
