name: Dependabot trigger after dependency changes

on:
  push:
    branches: [ master ]
    paths: [ 'pom.xml' ]

jobs:
  dependabot:

    runs-on: ubuntu-latest

    steps:
    - name: Check out a copy of repository in a workflow run
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'microsoft'
        
    - name: Get Maven version
      id: get_version
      run: |
        export POM=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo ::set-output name=version::$POM
        
    - name: Cut version using regex
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ steps.get_version.outputs.version }}
        regex: '^\d+\.\d+\.\d+$'
        
    - name: Check out my other repo
      uses: actions/checkout@main
      with:
        repository: actions-test-project
        token: ${{secrets.GITHUB_TOKEN}}
        
    - name: Dependabot Notify
      uses: alexanderj1988/dependabot-notify@v1.0.0
      with:
        github-access-token: ${{secrets.GITHUB_TOKEN}}
        dependency-name: "Viktor-Pylypenko/airslate-automation"
        dependency-version: "${{ steps.regex-match.outputs.match}}"
